fixed: race condition async and sync
Code was using async version of unlink, which was sometimes happening later, causing exceptions such as:

```
Error: ENOENT: no such file or directory, lstat 'mypath/myfile.js.map'
     at Object.lstatSync (fs.js:906:3)
     at /home/circleci/project/node_modules/ts-cleaner/index.js:55:43
     ...
```